### ISSUE TITLE
PHP tags throw Atom exception

### ISSUE THREAD

**Issue by brego** [dsandstrom/atom-double-tag#10]
1. The package explodes when used with code that blends PHP and html. Code example:
  ```php
  <form class="<?=$ifErrorFormVisible('first_name', 'last_name')?>">
  ```

2. When the cursor is positioned on the `<?` part, Atom throws exceptions.

**Atom Version**: 1.9.7
**System**: Mac OS X 10.11.6
**Thrown From**: [double-tag](https://github.com/dsandstrom/atom-double-tag) package, v0.2.0

### Stack Trace

Uncaught SyntaxError: Invalid regular expression: /<\/??=$ifErrorFormVisible('first_name',[>\s]/: Unterminated group

```
At /Users/brego/.atom/packages/double-tag/lib/double-tag.coffee:105

SyntaxError: Invalid regular expression: /<\/??=$ifErrorFormVisible('first_name',[>\s]/: Unterminated group
    at RegExp (native)
    at DoubleTag.module.exports.DoubleTag.findEndTag (/Users/brego/.atom/packages/double-tag/lib/double-tag.coffee:105:20)
    at DoubleTag.module.exports.DoubleTag.findTag (/Users/brego/.atom/packages/double-tag/lib/double-tag.coffee:42:20)
    at /Users/brego/.atom/packages/double-tag/lib/double-tag.coffee:22:8
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextEditor.module.exports.TextEditor.cursorMoved (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1928:27)
    at Selection.module.exports.Selection.markerDidChange (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:921:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:41:24
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at DisplayMarker.module.exports.DisplayMarker.notifyObservers (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-marker.js:245:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-marker.js:53:26
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Marker.module.exports.Marker.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:425:20)
    at Marker.module.exports.Marker.update (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:366:12)
    at Marker.module.exports.Marker.setHeadPosition (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:146:19)
    at DisplayMarker.module.exports.DisplayMarker.setHeadBufferPosition (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-marker.js:146:32)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:82:31
    at Cursor.module.exports.Cursor.changePosition (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:671:7)
    at Cursor.module.exports.Cursor.setBufferPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:80:19)
    at Cursor.module.exports.Cursor.moveToEndOfWord (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:351:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1796:23
    at TextEditor.module.exports.TextEditor.moveCursors (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1922:9)
    at TextEditor.module.exports.TextEditor.moveToEndOfWord (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1795:19)
    at TextEditor.commandRegistry.add.stopEventPropagation.editor:move-to-end-of-word (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:361:21)
    at atom-text-editor.newCommandListeners.(anonymous function) (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:642:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:55.2.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-ui-no-icons.theme-one-dark-syntax.theme-one-dark-ui)
  2x -0:11.7.0 core:close (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-ui-no-icons.theme-one-dark-syntax.theme-one-dark-ui)
     -0:05.2.0 core:move-left (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-ui-no-icons.theme-one-dark-syntax.theme-one-dark-ui)
  3x -0:04.7.0 core:move-down (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-ui-no-icons.theme-one-dark-syntax.theme-one-dark-ui)
     -0:01.8.0 core:move-up (atom-text-editor.editor.is-focused)
  9x -0:01.5.0 editor:move-to-end-of-word (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "allowPendingPaneItems": false,
    "disabledPackages": [
      "atom-autocomplete-php",
      "angularjs",
      "autocomplete-php",
      "git-diff-details",
      "merge-conflicts",
      "css-comb",
      "linter-htmlhint",
      "minimap-git-diff",
      "sync-settings",
      "minimap",
      "activate-power-mode"
    ],
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "Thumbs.db",
      ".codekit-cache",
      ".sass-cache"
    ],
    "packagesWithKeymapsDisabled": [
      "column-select"
    ]
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.7.3 (inactive)
aligner, v0.22.1 (active)
aligner-php, v1.0.0 (active)
aligner-scss, v1.1.0 (active)
angularjs, v0.3.5 (inactive)
atom-autocomplete-php, v0.18.9 (inactive)
autocomplete-php, v0.3.7 (inactive)
base16-dark-syntax, v0.1.0 (inactive)
block-comment, v0.4.3 (inactive)
change-case, v0.6.3 (active)
color-picker, v2.2.2 (active)
column-select, v0.2.0 (active)
css-comb, v2.5.0 (inactive)
css-snippets, v1.0.0 (active)
dash, v1.6.2 (inactive)
docblockr, v0.8.0 (active)
docs-snippets, v0.8.0 (active)
double-tag, v0.2.0 (active)
editorconfig, v1.4.1 (active)
file-icons, v1.7.18 (active)
firewatch-syntax, v1.0.1 (inactive)
git-blame, v0.4.11 (inactive)
git-diff-details, v1.3.0 (inactive)
javascript-snippets, v1.2.1 (active)
language-diff, v0.4.0 (active)
language-docker, v1.1.7 (active)
language-htaccess, v0.1.1 (active)
language-javascript-semantic, v0.2.1 (active)
language-nginx, v0.6.1 (active)
linter, v1.11.16 (active)
linter-htmlhint, v1.3.0 (inactive)
linter-jshint, v2.1.0 (active)
linter-jsonlint, v1.3.0 (active)
linter-php, v1.2.0 (active)
linter-scss-lint, v3.0.4 (active)
merge-conflicts, v1.4.4 (inactive)
minimap, v4.24.7 (inactive)
minimap-git-diff, v4.3.1 (inactive)
php-integrator-annotations, v1.0.1 (active)
php-integrator-autocomplete-plus, v1.0.4 (active)
php-integrator-base, v1.1.2 (active)
php-integrator-navigation, v1.0.2 (active)
php-integrator-tooltips, v1.0.1 (active)
pigments, v0.31.2 (active)
sort-lines, v0.14.0 (inactive)
sync-settings, v0.7.2 (inactive)
tabs-to-spaces, v1.0.2 (active)
todo-show, v1.7.0 (inactive)
twilight, v0.3.0 (inactive)
twilight-syntax, v0.7.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (active)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (active)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.0 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.0 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by dsandstrom** [comment]
Thanks for great repro steps.
