### ISSUE TITLE
Uncaught SyntaxError when adding br tag

### ISSUE THREAD

**Issue by jonyeezs** [dsandstrom/atom-double-tag#13]
[Enter steps to reproduce below:]

1. in a html file
2. type in <b
3. error pops up

It still closes the br tag properly, but pops up errors along the way

**Atom Version**: 1.10.2
**Electron Version**: 0.37.8
**System**: Microsoft Windows Server 2012 R2 Standard
**Thrown From**: [double-tag](https://github.com/dsandstrom/atom-double-tag) package, v0.4.0

### Stack Trace

Uncaught SyntaxError: Invalid regular expression: /<\/?b(Max.[>\s]/: Unterminated group

```
At /C:/Users/vagrant/.atom/packages/double-tag/lib/double-tag.coffee:136

SyntaxError: Invalid regular expression: /<\/?b(Max.[>\s]/: Unterminated group
    at RegExp (native)
    at DoubleTag.module.exports.DoubleTag.findEndTag (file:///C:/Users/vagrant/.atom/packages/double-tag/lib/double-tag.coffee:105:20)
    at DoubleTag.module.exports.DoubleTag.findTag (file:///C:/Users/vagrant/.atom/packages/double-tag/lib/double-tag.coffee:42:20)
    at file:///C:/Users/vagrant/.atom/packages/double-tag/lib/double-tag.coffee:22:8
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\vagrant\AppData\Local\atom\app-1.10.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\vagrant\AppData\Local\atom\app-1.10.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at TextEditor.module.exports.TextEditor.cursorMoved (C:\Users\vagrant\AppData\Local\atom\app-1.10.2\resources\app.asar\src\text-editor.js:1940:27)
    at Selection.module.exports.Selection.markerDidChange (C:\Users\vagrant\AppData\Local\atom\app-1.10.2\resources\app.asar\src\selection.js:921:21)
    at C:\Users\vagrant\AppData\Local\atom\app-1.10.2\resources\app.asar\src\selection.js:41:24
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\vagrant\AppData\Local\atom\app-1.10.2\resources\app.asar\node_modules\text-buffer\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\vagrant\AppData\Local\atom\app-1.10.2\resources\app.asar\node_modules\text-buffer\node_modules\event-kit\lib\emitter.js:129:28)
    at DisplayMarker.module.exports.DisplayMarker.notifyObservers (C:\Users\vagrant\AppData\Local\atom\app-1.10.2\resources\app.asar\node_modules\text-buffer\lib\display-marker.js:245:27)
    at C:\Users\vagrant\AppData\Local\atom\app-1.10.2\resources\app.asar\node_modules\text-buffer\lib\display-marker.js:53:26
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\vagrant\AppData\Local\atom\app-1.10.2\resources\app.asar\node_modules\text-buffer\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\vagrant\AppData\Local\atom\app-1.10.2\resources\app.asar\node_modules\text-buffer\node_modules\event-kit\lib\emitter.js:129:28)
    at Marker.module.exports.Marker.emitChangeEvent (C:\Users\vagrant\AppData\Local\atom\app-1.10.2\resources\app.asar\node_modules\text-buffer\lib\marker.js:425:20)
    at C:\Users\vagrant\AppData\Local\atom\app-1.10.2\resources\app.asar\node_modules\text-buffer\lib\marker-layer.js:293:25
    at Set.forEach (native)
    at MarkerLayer.module.exports.MarkerLayer.emitChangeEvents (C:\Users\vagrant\AppData\Local\atom\app-1.10.2\resources\app.asar\node_modules\text-buffer\lib\marker-layer.js:290:39)
    at TextBuffer.module.exports.TextBuffer.emitMarkerChangeEvents (C:\Users\vagrant\AppData\Local\atom\app-1.10.2\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1395:34)
    at TextBuffer.module.exports.TextBuffer.transact (C:\Users\vagrant\AppData\Local\atom\app-1.10.2\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:892:12)
    at TextEditor.module.exports.TextEditor.transact (C:\Users\vagrant\AppData\Local\atom\app-1.10.2\resources\app.asar\src\text-editor.js:1402:26)
    at C:\Users\vagrant\AppData\Local\atom\app-1.10.2\resources\app.asar\src\text-editor.js:979:24
    at TextEditor.module.exports.TextEditor.mergeSelections (C:\Users\vagrant\AppData\Local\atom\app-1.10.2\resources\app.asar\src\text-editor.js:2377:43)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (C:\Users\vagrant\AppData\Local\atom\app-1.10.2\resources\app.asar\src\text-editor.js:2343:35)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (C:\Users\vagrant\AppData\Local\atom\app-1.10.2\resources\app.asar\src\text-editor.js:977:19)
    at TextEditor.module.exports.TextEditor.insertText (C:\Users\vagrant\AppData\Local\atom\app-1.10.2\resources\app.asar\src\text-editor.js:943:19)
    at TextEditor.object.(anonymous function) [as insertText] (C:\Users\vagrant\AppData\Local\atom\app-1.10.2\resources\app.asar\node_modules\underscore-plus\lib\underscore-plus.js:77:27)
    at TextEditorComponent.module.exports.TextEditorComponent.onTextInput (C:\Users\vagrant\AppData\Local\atom\app-1.10.2\resources\app.asar\src\text-editor-component.js:516:26)
    at HTMLDivElement.<anonymous> (C:\Users\vagrant\AppData\Local\atom\app-1.10.2\resources\app.asar\src\text-editor-component.js:3:61)
```

### Commands

```
     -1:43.9.0 autoclose-html:close-and-complete (input.hidden-input)
  5x -0:44.7.0 core:backspace (input.hidden-input)
     -0:17.4.0 autoclose-html:close-and-complete (input.hidden-input)
     -0:05.2.0 core:move-right (input.hidden-input)
  7x -0:04.9.0 core:backspace (input.hidden-input)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "refactor",
      "symbols-view",
      "omnisharp-atom",
      "json-schema",
      "atom-yeoman",
      "wrap-guide",
      "styleguide"
    ],
    "openEmptyEditorOnStart": false,
    "packagesWithKeymapsDisabled": [
      "jasmine-runner",
      "tree-view",
      "git-time-machine",
      "git-line"
    ],
    "projectHome": "C:\\Development",
    "themes": [
      "atom-material-ui",
      "new-moon-atom-syntax"
    ]
  },
  "double-tag": {}
}
```

### Installed Packages

```coffee
# User
advanced-open-file, v0.16.4 (inactive)
aligner, v0.22.2 (active)
aligner-javascript, v1.0.0 (active)
aligner-ruby, v1.5.0 (active)
atom-beautify, v0.29.13 (active)
atom-material-ui, v1.3.6 (active)
atom-ternjs, v0.15.0 (active)
atom-visual-studio-code-ui, v1.3.4 (inactive)
autoclose-html, v0.23.0 (active)
autocomplete, v0.47.0 (inactive)
autocomplete-paths, v1.0.2 (active)
bottom-dock, v0.4.4 (active)
clipboard-history, v0.6.6 (inactive)
color-picker, v2.2.2 (active)
column-select, v0.2.0 (active)
docblockr, v0.8.5 (active)
double-tag, v0.4.0 (active)
editorconfig, v1.4.1 (active)
feedback, v0.38.0 (active)
file-icons, v1.7.19 (active)
git-history, v3.2.0 (inactive)
git-line, v0.5.0 (inactive)
git-log, v0.4.1 (active)
git-time-machine, v1.5.3 (inactive)
gulp-manager, v0.2.19 (active)
highlight-selected, v0.11.2 (active)
language-batch, v0.3.3 (active)
language-cshtml, v0.2.1 (active)
language-gherkin, v1.0.4 (active)
language-groovy, v0.6.0 (active)
language-powershell, v4.0.0 (active)
language-puppet, v0.21.0 (active)
linter, v1.11.18 (active)
linter-eslint, v7.3.2 (active)
linter-rubocop, v0.5.0 (active)
merge-conflicts, v1.4.4 (active)
minimap, v4.25.0 (active)
minimap-highlight-selected, v4.4.0 (active)
minimap-linter, v1.6.0 (active)
minitest-snippets, v0.2.0 (active)
new-moon-atom-syntax, v2.0.6 (active)
open-in-browser, v0.4.7 (inactive)
open-recent, v5.0.0 (active)
pretty-json, v1.6.0 (active)
ruby-block, v0.3.5 (active)
ruby-bundler, v0.3.0 (inactive)
save-session, v0.16.0 (active)
sync-settings, v0.7.2 (active)
tab-switcher, v1.5.3 (active)
todo-show, v1.7.0 (inactive)
xml-formatter, v0.10.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (inactive)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (inactive)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (inactive)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by dsandstrom** [comment]
Can you reproduce with the autoclose-html package disabled?  Maybe they are
incompatible.
