### ISSUE TITLE
Uncaught SyntaxError: Invalid regular expression

### ISSUE THREAD

**Issue by r-sierra** [dsandstrom/atom-double-tag#16]
Steps to reproduce:

1. In an html file
2. type (<i)
3. error pops up

**Atom Version**: 1.6.0
**System**: Fedora 25
**Thrown From**: [double-tag](https://github.com/dsandstrom/atom-double-tag) package, v0.4.0

### Stack Trace

Uncaught SyntaxError: Invalid regular expression: /<\/?i)[>\s]/: Unmatched ')'

```
At /home/fedora-user/.atom/packages/double-tag/lib/double-tag.coffee:105

SyntaxError: Invalid regular expression: /<\/?i)[>\s]/: Unmatched ')'
    at new RegExp (native)
    at DoubleTag.module.exports.DoubleTag.findEndTag (/home/fedora-user/.atom/packages/double-tag/lib/double-tag.coffee:105:20)
    at DoubleTag.module.exports.DoubleTag.findTag (/home/fedora-user/.atom/packages/double-tag/lib/double-tag.coffee:42:20)
    at /home/fedora-user/.atom/packages/double-tag/lib/double-tag.coffee:22:8
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextEditor.module.exports.TextEditor.cursorMoved (/usr/share/atom/resources/app.asar/src/text-editor.js:1685:27)
    at Selection.module.exports.Selection.markerDidChange (/usr/share/atom/resources/app.asar/src/selection.js:926:21)
    at /usr/share/atom/resources/app.asar/src/selection.js:41:24
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextEditorMarker.module.exports.TextEditorMarker.notifyObservers (/usr/share/atom/resources/app.asar/src/text-editor-marker.js:264:27)
    at /usr/share/atom/resources/app.asar/src/text-editor-marker.js:65:26
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Marker.module.exports.Marker.emitChangeEvent (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/marker.js:396:20)
    at /usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/marker-layer.js:299:27
    at Set.forEach (native)
    at MarkerLayer.module.exports.MarkerLayer.emitChangeEvents (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/marker-layer.js:295:46)
    at TextBuffer.module.exports.TextBuffer.emitMarkerChangeEvents (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1304:35)
    at TextBuffer.module.exports.TextBuffer.transact (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:825:12)
    at TextEditor.module.exports.TextEditor.transact (/usr/share/atom/resources/app.asar/src/text-editor.js:1243:26)
    at /usr/share/atom/resources/app.asar/src/text-editor.js:837:24
    at TextEditor.module.exports.TextEditor.mergeSelections (/usr/share/atom/resources/app.asar/src/text-editor.js:2123:18)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/usr/share/atom/resources/app.asar/src/text-editor.js:2085:35)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (/usr/share/atom/resources/app.asar/src/text-editor.js:835:19)
    at TextEditor.module.exports.TextEditor.insertText (/usr/share/atom/resources/app.asar/src/text-editor.js:801:19)
    at TextEditor.object.(anonymous function) [as insertText] (/usr/share/atom/resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:77:27)
    at TextEditorComponent.module.exports.TextEditorComponent.onTextInput (/usr/share/atom/resources/app.asar/src/text-editor-component.js:473:35)
    at HTMLDivElement.<anonymous> (/usr/share/atom/resources/app.asar/src/text-editor-component.js:3:61)
```

### Commands

```
     -1:40.7.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:40.7.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:28 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:26.8.0 core:save (atom-text-editor.editor.is-focused)
     -1:26.1.0 emmet:expand-abbreviation-with-tab (atom-text-editor.editor.is-focused)
     -1:25.3.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:25.1.0 emmet:expand-abbreviation-with-tab (atom-text-editor.editor.is-focused)
     -1:20.4.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
  4x -1:14.8.0 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:13.9.0 editor:select-to-end-of-word (atom-text-editor.editor.is-focused)
     -1:10.7.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
  2x -0:14.6.0 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:14 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:14 editor:newline (atom-text-editor.editor.is-focused)
     -0:11.1.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:09.1.0 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "automaticallyUpdate": false,
    "disabledPackages": [
      "metrics",
      "language-mustache",
      "language-objective-c",
      "language-toml",
      "spell-check",
      "about",
      "styleguide",
      "dev-live-reload",
      "package-generator",
      "archive-view",
      "open-on-github",
      "autosave",
      "linter-rails-best-practices"
    ],
    "packagesWithKeymapsDisabled": [
      "git-diff",
      "bracket-matcher",
      "linter"
    ],
    "projectHome": "/home/fedora-user/Code",
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-ionic2-framework, v0.3.2
color-picker, v2.2.3
double-tag, v0.4.0
emmet, v2.4.3
highlight-selected, v0.11.2
language-typescript-grammars-only, v1.5.0
linter, v1.11.18
linter-coffeescript, v1.0.0
pretty-json, v1.6.1

# Dev
No dev packages
```

**Comment by dsandstrom** [comment]
Thanks for submitting this, however I can't seem to reproduce.  Can you update to the latest Atom, you seem to have a pretty old version?  Also, can you reproduce with emmet disabled?  If updating doesn't resolved the problem, can you provide reproduction steps for a empty html file?

**Comment by r-sierra** [comment]
Updating to latest version(1.14.3) seems to solve the problem
